switch:
  - platform: template
    name: UART Logging
    id: uart_debug_switch
    restore_mode: ALWAYS_OFF
    optimistic: true
    turn_on_action:
      - logger.set_level: VERBOSE
    turn_off_action:
      - logger.set_level: ERROR